/* Central demo-concept copy, shared by portfolio mockups and interactive previews. */
window.SIGA_PROJECTS={
bg:{demo:'ДЕМО КОНЦЕПЦИЯ',browser:'siga2021 / демо концепция',write:'Пишете ни:',projects:{
watch:{title:'Часовници',navigation:'КОЛЕКЦИИ · ЗА НАС · ИСТОРИИ',eyebrow:'КОЛЕКЦИЯ / 001',headline:'Повече<br><i>от време.</i>',copy:'За хората, които ценят непреходното.',cta:'РАЗГЛЕДАЙ КОЛЕКЦИЯТА →',category:'Луксозни часовници / Онлайн магазин'},
restaurant:{title:'Ресторант',navigation:'МЕНЮ · НАШАТА ИСТОРИЯ · РЕЗЕРВАЦИИ',eyebrow:'ДЪРВО · ДИМ · ДУША',headline:'ХРАНАТА<br>СЪБИРА<br>ХОРАТА',copy:'Добра храна. Още по-добра компания.',cta:'РЕЗЕРВИРАЙ МАСА →',category:'Ресторант / Гостоприемство'},
architecture:{title:'Архитектура',navigation:'Проектиране · Архитектура',eyebrow:'ПРОЕКТ 001 / 285 М²',headline:'Пространства<br>за по-светло<br>утре',copy:'Съвременен живот.<br>Устойчиво бъдеще.',cta:'РАЗГЛЕДАЙ ПРОЕКТИТЕ →',category:'Архитектура / Недвижими имоти'}},
technical:{edition:'ИЗДАНИЕ / 001',object:'ОБЕКТ НА ВРЕМЕТО — 01',spec:'42 ММ / ЖЪЛТО ЗЛАТО / АВТОМАТИЧЕН МЕХАНИЗЪМ',form:'01 — ФОРМА / ФУНКЦИЯ',reserve:'72 Ч<br>РЕЗЕРВ НА ХОДА',permanent:'ПОСТОЯННА КОЛЕКЦИЯ',calibre:'КАЛИБЪР / 217 КОМПОНЕНТА',gold:'ЖЪЛТО ЗЛАТО',automatic:'АВТОМАТИЧЕН МЕХАНИЗЪМ',components:'КОМПОНЕНТА',atelier:'АТЕЛИЕ',edge:'ДЪРВО / ДИМ / ДУША — ДЕМО КОНЦЕПЦИЯ',kitchen:'КУХНЯ НА ОТКРИТ ОГЪН',flame:'НА ПЛАМЪК',dark:'СЛЕД ЗАЛЕЗ',living:'АРХИТЕКТУРА / ЖИВОТ',residential:'ПРОЕКТ 001 / ЖИЛИЩЕ',exterior:'001 / ЕКСТЕРИОР — ДНЕВНА СВЕТЛИНА',interior:'ИНТЕРИОР',space:'ОТКРИТО ПРОСТРАНСТВО'}},
de:{demo:'DEMO-KONZEPT',browser:'siga2021 / Demo-Konzept',write:'Schreiben Sie uns:',projects:{
watch:{title:'Uhren',navigation:'KOLLEKTIONEN · ÜBER UNS · JOURNAL',eyebrow:'KOLLEKTION / 001',headline:'Mehr<br><i>als Zeit.</i>',copy:'Für Menschen, die bleibende Werte schätzen.',cta:'KOLLEKTION ENTDECKEN →',category:'Luxusuhren / Onlinehandel'},
restaurant:{title:'Restaurant',navigation:'SPEISEKARTE · UNSERE GESCHICHTE · RESERVIERUNG',eyebrow:'HOLZ · RAUCH · SEELE',headline:'ESSEN<br>BRINGT UNS<br>ZUSAMMEN',copy:'Gutes Essen. Noch bessere Gesellschaft.',cta:'TISCH RESERVIEREN →',category:'Restaurant / Gastronomie'},
architecture:{title:'Architektur',navigation:'Planung · Architektur',eyebrow:'PROJEKT 001 / 285 M²',headline:'Räume<br>für eine bessere<br>Zukunft',copy:'Modernes Wohnen.<br>Nachhaltige Zukunft.',cta:'PROJEKTE ENTDECKEN →',category:'Architektur / Immobilien'}},
technical:{edition:'EDITION / 001',object:'OBJEKT DER ZEIT — 01',spec:'42 MM / GELBGOLD / AUTOMATIK',form:'01 — FORM / FUNKTION',reserve:'72 H<br>GANGRESERVE',permanent:'DAUERHAFTE KOLLEKTION',calibre:'KALIBER / 217 KOMPONENTEN',gold:'GELBGOLD',automatic:'AUTOMATIK',components:'KOMPONENTEN',atelier:'ATELIER',edge:'HOLZ / RAUCH / SEELE — DEMO-KONZEPT',kitchen:'KÜCHE AM OFFENEN FEUER',flame:'ÜBER DER FLAMME',dark:'NACH EINBRUCH DER DUNKELHEIT',living:'ARCHITEKTUR / WOHNEN',residential:'PROJEKT 001 / WOHNHAUS',exterior:'001 / AUSSENANSICHT — TAGESLICHT',interior:'INNENRAUM',space:'FREIRAUM'}},
en:{demo:'DEMO CONCEPT',browser:'siga2021 / demo concept',write:'Email us:',projects:{
watch:{title:'Watches',navigation:'COLLECTIONS · ABOUT · JOURNAL',eyebrow:'COLLECTION / 001',headline:'More<br><i>than time.</i>',copy:'For those who value what lasts.',cta:'EXPLORE COLLECTION →',category:'Luxury Watches / E-commerce'},
restaurant:{title:'Restaurant',navigation:'MENU · OUR STORY · RESERVATIONS',eyebrow:'WOOD · SMOKE · SOUL',headline:'FOOD<br>BRINGS PEOPLE<br>CLOSER',copy:'Good food. Better company.',cta:'RESERVE A TABLE →',category:'Restaurant / Hospitality'},
architecture:{title:'Architecture',navigation:'Design · Architecture',eyebrow:'PROJECT 001 / 285 M²',headline:'Spaces<br>for a brighter<br>tomorrow',copy:'Modern living.<br>Sustainable future.',cta:'EXPLORE PROJECTS →',category:'Architecture / Real Estate'}},
technical:{edition:'EDITION / 001',object:'OBJECT OF TIME — 01',spec:'42 MM / YELLOW GOLD / AUTOMATIC',form:'01 — FORM / FUNCTION',reserve:'72 H<br>POWER RESERVE',permanent:'PERMANENT COLLECTION',calibre:'CALIBRE / 217 COMPONENTS',gold:'YELLOW GOLD',automatic:'AUTOMATIC',components:'COMPONENTS',atelier:'ATELIER',edge:'WOOD / SMOKE / SOUL — DEMO CONCEPT',kitchen:'OPEN FIRE KITCHEN',flame:'OVER THE FLAME',dark:'AFTER DARK',living:'ARCHITECTURE / LIVING',residential:'PROJECT 001 / RESIDENTIAL',exterior:'001 / EXTERIOR — DAYLIGHT',interior:'INTERIOR',space:'OPEN SPACE'}}
};
(()=>{const t=window.SIGA_PROJECTS[document.documentElement.lang]||window.SIGA_PROJECTS.en;const keys=['watch','restaurant','architecture'];document.querySelectorAll('.showcase-panel').forEach((panel,i)=>{const p=t.projects[keys[i]];if(!p)return;const set=(s,v)=>{const e=panel.querySelector(s);if(e)e.innerHTML=v;};set('h3',p.title);set('.showcase-meta small',t.demo);set('.mini-site-nav strong',p.title);set('.mini-site-nav>span',p.navigation);set('.mini-site-copy small',p.eyebrow);set('.mini-site-copy h4',p.headline);set('.mini-site-copy p',p.copy);set('.mini-cta',p.cta);set('.mini-demo',t.demo);set('.browser-chrome>span:nth-child(2)',t.browser);set('.showcase-caption>span',p.category);const caption=panel.querySelector('.showcase-caption');if(caption)caption.dataset.title=p.title;const img=panel.querySelector('.mini-site-content img');if(img)img.alt=p.title+' — '+t.demo;});})();
